export const ROLES = {
  GLOBAL_ADMIN: 'GLOBAL_ADMIN',
  BLUE_TEAM: 'BLUE_TEAM',
  RED_TEAM: 'RED_TEAM',
  GRC: 'GRC',
  SOC_ANALYST: 'SOC_ANALYST',
  SOC_MANAGER: 'SOC_MANAGER',
  PHISHING_MANAGER: 'PHISHING_MANAGER',
  PHISHING_OPERATOR: 'PHISHING_OPERATOR',
  AUDITOR: 'AUDITOR',
};

export const ROLE_LABELS = {
  GLOBAL_ADMIN: 'Global Admin',
  BLUE_TEAM: 'Blue Team',
  RED_TEAM: 'Red Team',
  GRC: 'GRC',
  SOC_ANALYST: 'SOC Analyst',
  SOC_MANAGER: 'SOC Manager',
  PHISHING_MANAGER: 'Phishing Manager',
  PHISHING_OPERATOR: 'Phishing Operator',
  AUDITOR: 'Auditor',
};

export const tools = [
  {
    id: 'grc',
    name: 'GRC',
    path: '/GRC',
    icon: 'shield-check',
    roles: ['GLOBAL_ADMIN', 'GRC'],
    features: [
      { id: 'dashboard',    name: 'Dashboard',   path: '/GRC',             icon: 'layout-dashboard' },
      { id: 'audits',       name: 'Audits',      path: '/GRC/Audits',      icon: 'clipboard-check'  },
      { id: 'standards',    name: 'Standards',   path: '/GRC/Standards',   icon: 'file-badge'       },
      { id: 'remediation',  name: 'Remediation', path: '/GRC/Remediation', icon: 'wrench'           },
      { id: 'settings',     name: 'Settings',    path: '/GRC/Settings',    icon: 'settings'         },
    ],
  },
  {
    id: 'soar',
    name: 'SOAR',
    path: '/SOAR',
    icon: 'zap',
    roles: ['GLOBAL_ADMIN', 'BLUE_TEAM', 'SOC_ANALYST'],
    features: [
      { id: 'analytics',   name: 'Analytics & Reports',  path: '/SOAR',                    icon: 'bar-chart-2'   },
      { id: 'incidents',   name: 'Incidents Queue',      path: '/SOAR/IncidentsQueue',     icon: 'triangle-alert' },
      { id: 'management',  name: 'Incident Management',  path: '/SOAR/IncidentManagement', icon: 'folder-open'   },
      { id: 'playbook',    name: 'Playbook Builder',     path: '/SOAR/playbook',           icon: 'wrench'        },
    ],
  },
  {
    id: 'threat-intel',
    name: 'Threat Intelligence',
    path: '/ThreatIntel',
    icon: 'crosshair',
    roles: ['GLOBAL_ADMIN', 'BLUE_TEAM', 'SOC_ANALYST'],
    features: [
      { id: 'feeds',      name: 'Feeds',      path: '/ThreatIntel/Feeds',      icon: 'rss'       },
      { id: 'indicators', name: 'Indicators', path: '/ThreatIntel/Indicators', icon: 'target'    },
      { id: 'reports',    name: 'Reports',    path: '/ThreatIntel/Reports',    icon: 'file-text' },
    ],
  },
  {
    id: 'phishing',
    name: 'Phishing Simulator',
    path: '/Phishing',
    icon: 'mail-warning',
    roles: [
      'GLOBAL_ADMIN',
      'RED_TEAM',
      'PHISHING_MANAGER',
      'PHISHING_OPERATOR',
      'SOC_ANALYST',
      'SOC_MANAGER',
      'AUDITOR',
    ],
    features: [
      { id: 'dashboard',      name: 'Dashboard',     path: '/Phishing',                        icon: 'layout-dashboard' },
      { id: 'dashboard-risks', name: 'Risks',        path: '/Phishing/Dashboard/Risks',        icon: 'triangle-alert'   },
      { id: 'dashboard-depts', name: 'Departments',  path: '/Phishing/Dashboard/Departments', icon: 'building-2'       },
      { id: 'dashboard-trends', name: 'Trends',      path: '/Phishing/Dashboard/Trends',       icon: 'trending-up'      },
      { id: 'campaigns',      name: 'Campaigns',     path: '/Phishing/Campaigns',              icon: 'send'             },
      { id: 'templates',      name: 'Templates',     path: '/Phishing/Templates',              icon: 'layout'           },
      { id: 'landing-pages',  name: 'Landing Pages', path: '/Phishing/LandingPages',           icon: 'globe'            },
      { id: 'recipients',     name: 'Recipients',    path: '/Phishing/Recipients',             icon: 'users'            },
      { id: 'tracking-logs',  name: 'Tracking Logs', path: '/Phishing/Tracking/Logs',        icon: 'list'             },
      { id: 'tracking-timeline', name: 'Timeline',   path: '/Phishing/Tracking/Timeline',      icon: 'eye'              },
      { id: 'reports',        name: 'Reports',       path: '/Phishing/Reports',                icon: 'file-text'        },
      { id: 'settings',       name: 'Settings',      path: '/Phishing/Settings',               icon: 'settings'         },
    ],
  },
  {
    id: 'network',
    name: 'Network Scanner',
    path: '/Network',
    icon: 'network',
    roles: ['GLOBAL_ADMIN', 'RED_TEAM'],
    features: [
      { id: 'dashboard',        name: 'Dashboard',          path: '/Network',                     icon: 'layout-dashboard' },
      { id: 'discovery',        name: 'Network Discovery',  path: '/Network/NetworkDiscovery',    icon: 'search'           },
      { id: 'port-scanning',    name: 'Port Scanning',      path: '/Network/PortScanning',        icon: 'scan-line'        },
      { id: 'packet-capture',   name: 'Packet Capture',     path: '/Network/PacketCapture',       icon: 'activity'         },
      { id: 'asset-inventory',  name: 'Asset Inventory',    path: '/Network/AssetInventory',      icon: 'server'           },
      { id: 'misconfigs',       name: 'Misconfigurations',  path: '/Network/Misconfigurations',   icon: 'alert-circle'     },
      { id: 'flow-monitoring',  name: 'Flow Monitoring',    path: '/Network/FlowMonitoring',      icon: 'git-branch'       },
    ],
  },
];
